### PR TITLE
Add charts page aa1 to implement aa1

### PR DESCRIPTION
**Pull request by pinterid**
**Checklist:**

 

 - [x] Have you added an explanation of what your changes do and why you'd like them to be included?
 - [x] Have you updated or added documentation for the change?
 - [x] Have you tested your changes with successful results?

**Type of Changes:**

 

 - [ ] Bug fix (non-breaking change which fixes an issue)
 - [x] New feature (non-breaking change which adds functionality)
 - [ ] Breaking change (fix or feature that would cause existing functionality to change)

**What is the current behavior? (link to any open issues here)**
- Currently there is no template for displaying burn down charts.
- Currently there is no template for displaying throughput charts.
- Currently the landing page template has no dummy data.

**What is the new behavior (if this is a feature change)?**
- Now there is an template for displaying burn down charts.
- Now there is an template for displaying throughput charts.
- Now the landing page template has dummy data.

**Other information**:
- Screenshots of the implemented changes:

***Throughput Chart***
By clicking on of the issues, the clicked issue won't be displayed.
image

***Burn Down Chart***
By clicking on of the issues, the clicked issue won't be displayed.
image

### CODE REVIEW

**Review by Aichnerc — APPROVED** [review]
LGTM

**Review by schettn — APPROVED** [review]
lgtm

**Review by kleberbaum — APPROVED** [review]
Should be ok to merge.

**Review by Aichnerc — APPROVED** [review]
LGTM

**Pull request merged**
